import React from "react";
import { PreserveScroll } from '../lib';

interface Page1Props {
  preserveScrollDisabled: boolean
}

export const Page1: React.FC<Page1Props> = function Page1({ preserveScrollDisabled }) {
  const Tag = preserveScrollDisabled ? 'div' : PreserveScroll;
  return (
    <Tag id='scroller'>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Porttitor massa id neque aliquam vestibulum morbi blandit. Feugiat in ante metus dictum at. Tortor posuere ac ut consequat. Arcu felis bibendum ut tristique et. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Massa tempor nec feugiat nisl. Risus in hendrerit gravida rutrum. Praesent tristique magna sit amet purus gravida quis blandit. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Eget lorem dolor sed viverra. Erat pellentesque adipiscing commodo elit at imperdiet. In iaculis nunc sed augue lacus viverra vitae congue. Ut etiam sit amet nisl purus in mollis nunc. Tortor condimentum lacinia quis vel eros donec ac odio tempor. Et tortor at risus viverra. Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu. Interdum varius sit amet mattis vulputate. Integer enim neque volutpat ac tincidunt.</p>
      <p>Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra. Tincidunt arcu non sodales neque. Neque viverra justo nec ultrices dui sapien eget mi. Tellus rutrum tellus pellentesque eu tincidunt tortor. Eget est lorem ipsum dolor sit amet. Eget egestas purus viverra accumsan in. Tellus in metus vulputate eu scelerisque. Cursus metus aliquam eleifend mi. Feugiat in ante metus dictum at.</p>
      <p>Eleifend donec pretium vulputate sapien nec sagittis. Mi tempus imperdiet nulla malesuada pellentesque. Fringilla ut morbi tincidunt augue interdum. Vel quam elementum pulvinar etiam non quam. Tincidunt eget nullam non nisi. Urna molestie at elementum eu facilisis sed odio morbi quis. Risus at ultrices mi tempus imperdiet. Imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor. Posuere sollicitudin aliquam ultrices sagittis orci. Dui nunc mattis enim ut. Magna ac placerat vestibulum lectus mauris. Integer feugiat scelerisque varius morbi enim nunc. Natoque penatibus et magnis dis parturient montes. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse.</p>
      <p>Rhoncus dolor purus non enim praesent elementum facilisis. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt. Nunc sed id semper risus in hendrerit gravida rutrum. Blandit massa enim nec dui nunc. Nam libero justo laoreet sit amet cursus sit amet dictum. Bibendum at varius vel pharetra vel turpis nunc eget lorem. Pretium vulputate sapien nec sagittis. Hendrerit dolor magna eget est lorem. Eget gravida cum sociis natoque penatibus et magnis dis. Sed tempus urna et pharetra pharetra massa. Quis enim lobortis scelerisque fermentum dui faucibus.</p>
      <p>Mauris augue neque gravida in fermentum et sollicitudin ac. Eget velit aliquet sagittis id consectetur purus. In nisl nisi scelerisque eu ultrices vitae auctor eu augue. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Ut tortor pretium viverra suspendisse potenti nullam ac. Eget velit aliquet sagittis id consectetur purus ut faucibus. Ullamcorper eget nulla facilisi etiam dignissim diam. Faucibus nisl tincidunt eget nullam non. Nisi lacus sed viverra tellus in hac. Non tellus orci ac auctor. Eu turpis egestas pretium aenean pharetra magna ac. Augue neque gravida in fermentum. Elit ut aliquam purus sit amet.</p>
      <p>Gravida neque convallis a cras semper auctor neque vitae tempus. Ac feugiat sed lectus vestibulum mattis. Quisque egestas diam in arcu cursus euismod quis. Tincidunt praesent semper feugiat nibh sed pulvinar. Nunc sed blandit libero volutpat. Massa enim nec dui nunc mattis enim. Elementum curabitur vitae nunc sed velit dignissim sodales ut eu. Cras tincidunt lobortis feugiat vivamus at augue eget arcu. Feugiat in fermentum posuere urna nec tincidunt praesent semper feugiat. Sodales ut eu sem integer vitae justo eget magna fermentum. Pharetra massa massa ultricies mi quis hendrerit dolor. Ut sem viverra aliquet eget sit amet tellus cras. Neque egestas congue quisque egestas. Integer vitae justo eget magna fermentum iaculis. Cursus risus at ultrices mi tempus. Mattis enim ut tellus elementum sagittis. Ipsum a arcu cursus vitae congue mauris rhoncus. Proin sed libero enim sed faucibus. Egestas integer eget aliquet nibh praesent tristique magna sit amet. Ut placerat orci nulla pellentesque dignissim enim sit amet venenatis.</p>
      <p>Porta lorem mollis aliquam ut porttitor leo. Nec ultrices dui sapien eget mi proin. Varius quam quisque id diam vel quam elementum pulvinar etiam. Et tortor consequat id porta. Maecenas ultricies mi eget mauris pharetra et ultrices neque ornare. Convallis tellus id interdum velit laoreet id donec ultrices. Pharetra sit amet aliquam id diam. Urna et pharetra pharetra massa massa ultricies mi. Diam donec adipiscing tristique risus nec feugiat in fermentum posuere. Sit amet nulla facilisi morbi tempus iaculis urna id volutpat. Dignissim enim sit amet venenatis. In eu mi bibendum neque egestas congue quisque. Nunc aliquet bibendum enim facilisis gravida neque convallis a cras. Risus in hendrerit gravida rutrum quisque non tellus orci. Sit amet nisl suscipit adipiscing bibendum est. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Tempor commodo ullamcorper a lacus vestibulum sed arcu. Ipsum dolor sit amet consectetur adipiscing elit.</p>
      <p>Eget nullam non nisi est sit amet facilisis magna etiam. Mattis rhoncus urna neque viverra. Eros in cursus turpis massa tincidunt dui. Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu. Id diam vel quam elementum pulvinar. Risus quis varius quam quisque. Ornare arcu odio ut sem nulla pharetra diam. Proin libero nunc consequat interdum varius sit. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Ornare massa eget egestas purus viverra accumsan in. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim. Suspendisse potenti nullam ac tortor vitae purus. Etiam erat velit scelerisque in dictum non consectetur a erat. Enim tortor at auctor urna. Viverra ipsum nunc aliquet bibendum enim facilisis.</p>
      <p>Venenatis urna cursus eget nunc scelerisque viverra. Facilisis gravida neque convallis a cras semper auctor neque. Auctor neque vitae tempus quam pellentesque nec nam. Malesuada bibendum arcu vitae elementum curabitur. Habitant morbi tristique senectus et netus et malesuada fames. Blandit volutpat maecenas volutpat blandit. Et netus et malesuada fames ac turpis egestas sed. Amet mattis vulputate enim nulla aliquet porttitor. Fames ac turpis egestas integer eget aliquet nibh praesent. Vitae ultricies leo integer malesuada nunc vel risus commodo.</p>
      <p>Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Nunc sed blandit libero volutpat. Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Sit amet nisl suscipit adipiscing bibendum. Et odio pellentesque diam volutpat. Nulla pellentesque dignissim enim sit amet venenatis urna cursus eget. Elit sed vulputate mi sit amet mauris commodo quis imperdiet. Ornare suspendisse sed nisi lacus. Tempor orci eu lobortis elementum nibh tellus molestie nunc. Lobortis scelerisque fermentum dui faucibus in ornare. Sed tempus urna et pharetra. Massa vitae tortor condimentum lacinia. Ipsum faucibus vitae aliquet nec.</p>
    </Tag>
  );
}